MakeUpDefinitions = MakeUpDefinitions or {};

-- define all categories for make up
MakeUpDefinitions.MakeUpDefinitions = {};
--cat = {};
--cat.name = "Lips";
--cat.avatarZoom = 23.5;
--cat.avatarYOffset = -0.83;
--cat.avatarXOffset = 0.004;
--cat.category = "Lips";
--MakeUpDefinitions.categories["Lips"] = cat;
--cat = {};
--cat.name = "ZoomOut";
--cat.avatarZoom = 13.5;
--cat.avatarYOffset = -0.83;
--cat.avatarXOffset = 0.004;
--cat.category = "Lips";
--MakeUpDefinitions.categories["Lips"] = cat;
--cat = {};
--cat.name = "ZoomIn";
--cat.avatarZoom = 17.5;
--cat.avatarYOffset = -0.53;
--cat.avatarXOffset = 0.004;
--cat.category = "Lips";
--MakeUpDefinitions.categories["Lips"] = cat;

-- FULL FACE
local makeup = {};
makeup.name = "FullFaceClownFace1Color";
makeup.category = "FullFace";
makeup.item = "AuthenticZClothing.MakeUp_ClownFace1Color";
makeup.makeuptypes = {};
makeup.makeuptypes["All"] = true;
makeup.makeuptypes["Foundation"] = true;
table.insert(MakeUpDefinitions.makeup, makeup);
makeup = {};
makeup.name = "FullFaceClownFace2Color";
makeup.category = "FullFace";
makeup.item = "AuthenticZClothing.MakeUp_ClownFace2Color";
makeup.makeuptypes = {};
makeup.makeuptypes["All"] = true;
makeup.makeuptypes["Foundation"] = true;
table.insert(MakeUpDefinitions.makeup, makeup);
makeup = {};
makeup.name = "FullFaceInsane";
makeup.category = "FullFace";
makeup.item = "AuthenticZClothing.MakeUp_Insane";
makeup.makeuptypes = {};
makeup.makeuptypes["All"] = true;
makeup.makeuptypes["Foundation"] = true;
table.insert(MakeUpDefinitions.makeup, makeup);
makeup = {};
makeup.name = "FullFaceJoker";
makeup.category = "FullFace";
makeup.item = "AuthenticZClothing.MakeUp_Joker";
makeup.makeuptypes = {};
makeup.makeuptypes["All"] = true;
makeup.makeuptypes["Foundation"] = true;
table.insert(MakeUpDefinitions.makeup, makeup);
makeup = {};
makeup.name = "FullFaceJokerColor";
makeup.category = "FullFace";
makeup.item = "AuthenticZClothing.MakeUp_JokerColor";
makeup.makeuptypes = {};
makeup.makeuptypes["All"] = true;
makeup.makeuptypes["Foundation"] = true;
table.insert(MakeUpDefinitions.makeup, makeup);
makeup = {};
makeup.name = "FullFaceMimeBlack";
makeup.category = "FullFace";
makeup.item = "AuthenticZClothing.MakeUp_MimeBlack";
makeup.makeuptypes = {};
makeup.makeuptypes["All"] = true;
makeup.makeuptypes["Foundation"] = true;
table.insert(MakeUpDefinitions.makeup, makeup);
makeup = {};
makeup.name = "FullFaceMimeRed";
makeup.category = "FullFace";
makeup.item = "AuthenticZClothing.MakeUp_MimeRed";
makeup.makeuptypes = {};
makeup.makeuptypes["All"] = true;
makeup.makeuptypes["Foundation"] = true;
table.insert(MakeUpDefinitions.makeup, makeup)

