require 'Definitions/HairOutfitDefinitions'
-- To Dos add more comments on hair colors. 

--Vanilla Fixes--

local cat = {};
cat.outfit = "VarsityFemale";
cat.haircut = "Hat:5;OverEye:5;Bun:5;Back:5;Long:5;Kate:5;Long2:5;Ponytail:5;Longcurly:5;Long2curly:5;BobCurly:5;KateCurly:5;OverEyeCurly:5;RachelCurly:5;ShortCurly:5;Rachel:5;CentrePartingLong:5;Grungey:5;GrungeyParted:5;Cornrows:5";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "VarsityMale";
cat.haircut = "Short:10;Messy:5;MessyCurly:5;CrewCut:5;Donny:5;Mullet:5;MulletCurly:5;Metal:5;Fabian:5;FabianCurly:5;ShortAfroCurly:5;ShortHatCurly:5;CentreParting:5;LeftParting:5;RightParting:5;CentreParting:5;Fresh:5;LibertySpikes:5;MohawkSpike:5";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "StudentMale";
cat.haircut = "Short:10;Messy:5;MessyCurly:5;CrewCut:5;Donny:5;Mullet:5;MulletCurly:5;Metal:5;Fabian:5;FabianCurly:5;ShortAfroCurly:5;ShortHatCurly:5;CentreParting:5;LeftParting:5;RightParting:5;CentreParting:5;Fresh:5;LibertySpikes:5;MohawkSpike:5";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "StudentFemale";
cat.haircut = "Hat:5;OverEye:5;Bun:5;Back:5;Long:5;Kate:5;Long2:5;Ponytail:5;Longcurly:5;Long2curly:5;BobCurly:5;KateCurly:5;OverEyeCurly:5;RachelCurly:5;ShortCurly:5;Rachel:5;CentrePartingLong:5;Grungey:5;GrungeyParted:5;Cornrows:5";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
-- End of Vanilla fixes --

local cat = {};
cat.outfit = "AuthenticAbeLincoln";
cat.haircut = "Short:100";
cat.beard = "BeardOnly:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticAndyDotD";
cat.haircut = "Ponytail:100";
cat.beard = "None:100";
cat.haircutColor = "0.52,0.37,0.26:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticAshEvilDead";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticB4BEvangelo";
cat.haircut = "ShortAfroCurly:100";
cat.beard = "None:100";
cat.haircutColor = "0.60,0.46,0.30:100"; -- Duller Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticB4BHoffman";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100" --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticB4BHolly";
cat.haircut = "Ponytail:100";
cat.beard = "None:100";
cat.haircutColor = "0.80,0.44,0.33:100";  -- Salmon
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticB4BMom";
cat.haircut = "Ponytail:100";
cat.beard = "None:100";
cat.haircutColor = "0.80,0.80,0.80:100"; --grey/white
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticB4BWalker";
cat.haircut = "Short:100";
cat.beard = "Full:100";
cat.haircutColor = "0.10,0.01,0.05:100" -- Black
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticBigDaddy";
cat.haircut = "Bald:100";
cat.beard = "Goatee:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticBillOverbeck";
cat.haircut = "Short:100";
cat.beard = "BeardOnly:100";
cat.haircutColor = "0.80,0.80,0.80:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticBillMurray";
cat.haircut = "Buffont:100";
cat.beard = "none:100";
cat.haircutColor = "0.60,0.46,0.30:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticBillyChumpez";
cat.haircut = "Messy:100";
cat.beard = "Long:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticBlackMamba";
cat.haircut = "Long:100";
cat.beard = "none:100";
cat.haircutColor = "0.99,0.92,0.55:100"; -- Blonde
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticBobRoss";
cat.haircut = "ShortAfroCurly:100";
cat.beard = "Chin:100";
cat.haircutColor = "0.60,0.46,0.30:100"
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticBub";
cat.haircut = "Recede:100";
cat.beard = "None:100";
cat.haircutColor = "0.60,0.46,0.30:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticCharcoal";
cat.haircut = "Bald:100";
cat.beard = "None:100";
cat.haircutColor = "0.60,0.46,0.30:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticClementine";
cat.haircut = "Ponytail:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.14,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticClownBarotrauma";
cat.haircut = "Balding:100";
cat.beard = "None:100"; --gummi Yellow    MarsYellow
cat.haircutColor = "0.89,0.44,0.10:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticClown";
cat.haircut = "Balding:100";
cat.beard = "None:100";--Turqoise,         Purple        SeaGreen             Red           gummi Yellow    PackerGold          MarsYellow       Royal Blue
cat.haircutColor = "0,0.90,0.93:12;0.40,0.99,0.40:14;0.75,0.24,0.99:12;0.89,0.07,0.19:14;0.98,0.86,0.05:12;0.99,0.71,0.08:12;0.89,0.44,0.10:12;0.20,0.20,0.99:12";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticClownMime";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticCoach";
cat.haircut = "Bald:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticCFTDJim";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.60,0.46,0.30:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticChainsawMaid";
cat.haircut = "Rachel:100";
cat.beard = "None:100";
cat.haircutColor = "0.10,0.01,0.05:100" -- Black
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticCheerleader";
cat.haircut = "Hat:5;OverEye:5;Bun:6;Back:6;Long:6;Kate:5;Long2:6;Ponytail:6;Longcurly:5;Long2curly:6;BobCurly:5;KateCurly:6;OverEyeCurly:5;RachelCurly:5;Rachel:6;CentrePartingLong:5;Grungey:6;GrungeyParted:6";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticClownPennywise";
cat.haircut = "Bald:100";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDianneCaldwell";
cat.haircut = "Long:100";
cat.beard = "None:100";
cat.haircutColor = "0.99,0.92,0.55:100"; -- Blonde
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDIJohnMorgan";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDILoganCarter";
cat.haircut = "CrewCut:100";
cat.beard = "Goatee:100";
cat.haircutColor = "0.60,0.46,0.30:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDIPurnaJackson";
cat.haircut = "Braids:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDISamB";
cat.haircut = "Bald:100";
cat.beard = "None:100";
cat.haircutColor ="0.10,0.01,0.05:100" --Black Color
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDIXianMei";
cat.haircut = "Grungey:100";
cat.beard = "None:100";
cat.haircutColor = "0.10,0.01,0.05:100" --Black Color
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDocBrown";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.90,0.90,0.90:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDRBradGarrison";
cat.haircut = "Bald:100";
cat.beard = "ThinMoustache:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDRChuckGreene";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.99,0.92,0.55:100"; -- Blonde
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDRFrankWest";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDRJessieMcCarney";
cat.haircut = "Grungey:100";
cat.haircutColor = "0.99,0.92,0.55:100"; -- Blonde
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticDukeNukem";
cat.haircut = "DukeBuzzCut:100";
cat.beard = "None:100";
cat.haircutColor = "0.99,0.92,0.55:100"; -- Blonde
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticEllis";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.82,0.71,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticErinFontaine";
cat.haircut = "Long:100";
cat.beard = "None:100";
cat.haircutColor = "0.10,0.01,0.05:100"
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticFlyboy";
cat.haircut = "LeftParting:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticFrancis";
cat.haircut = "CrewCut:100";
cat.beard = "Goatee:100";
cat.haircutColor = "0.33,0.16,0.16:100"
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticFreddyKrueger";
cat.haircut = "Bald:100";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticFreshPrinceBelAir";
cat.haircut = "Bald:100";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGordonFreeman";
cat.haircut = "Short:100";
cat.beard = "Goatee:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGrindhouseCherry";
cat.haircut = "Long2:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGMan";
cat.haircut = "Recede:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGhostFace";
cat.haircut = "Bald:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100" --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGhostbusterSpengler";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100" --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGhostbusterStantz";
cat.haircut = "Recede:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGhostbusterVenkman";
cat.haircut = "Recede:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticGhostbusterZeddemore";
cat.haircut = "Short:100";
cat.beard = "ThinMoustache:100";
cat.haircutColor = "0.10,0.01,0.05:100" -- Black
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticHankHill";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat); 
local cat = {};
cat.outfit = "AuthenticHalloween";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; 
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticJasonPart2";
cat.haircut = "Mullet:100";
cat.beard = "None:100";
cat.haircutColor = "0.82,0.71,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticJasonPart3";
cat.haircut = "None:100";
cat.beard = "None:100";
cat.haircutColor = "0.82,0.71,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticJillValentine";
cat.haircut = "OverEye:100";
cat.haircutColor = "0.60,0.46,0.30:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticJimmyGibbs";
cat.haircut = "Short:100";
cat.beard = "Goatee:100";
cat.haircutColor = "0.80,0.80,0.80:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticJoker";
cat.haircut = "Mullet:100";
cat.beard = "None:100";
cat.haircutColor = "0.00,0.69,0.20:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticKleiner";
cat.haircut = "Picard:100";
cat.beard = "None:100";
cat.haircutColor = "0.35,0.35,0.35:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticLadyD";
cat.haircut = "RachelCurly:100";
cat.haircutColor ="0.10,0.01,0.05:100" --Black Color
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticLeatherFace";
cat.haircut = "MessyCurly:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticLeonKennedy";
cat.haircut = "LeftParting:100";
cat.beard = "None:100";
cat.haircutColor = "0.82,0.71,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticLouis";
cat.haircut = "Bald:100";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticMadMax";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticMaid";
cat.haircut = "Hat:5;OverEye:5;Bun:6;Back:6;Long:6;Kate:5;Long2:6;Ponytail:6;Longcurly:5;Long2curly:6;BobCurly:5;KateCurly:6;OverEyeCurly:5;RachelCurly:5;Rachel:6;CentrePartingLong:5;Grungey:6;GrungeyParted:6";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticMartyMcFly";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.60,0.46,0.30:100"
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNateAnderson";
cat.haircut = "CrewCut:100";
cat.beard = "Goatee:100";
cat.haircutColor = "0.33,0.16,0.16:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNeonFitnessInstructor";
cat.haircut = "Hat:5;OverEye:5;Bun:5;Back:5;Long:5;Kate:5;Long2:5;Ponytail:5;Longcurly:5;Long2curly:5;BobCurly:5;KateCurly:5;OverEyeCurly:5;RachelCurly:5;ShortCurly:5;Rachel:5;CentrePartingLong:5;Grungey:5;GrungeyParted:5;Cornrows:5";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNick";
cat.haircut = "Recede:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHBadass";
cat.haircut = "Back:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHBateman";
cat.haircut = "Recede:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHButcher";
cat.haircut = "Picard:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHHunter";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHJive";
cat.haircut = "BigAfro:100";
cat.beard = "None:100";
cat.haircutColor = "0.10,0.01,0.05:100" -- Black
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHMolotov";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHRoje";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.10,0.01,0.05:100" -- Black
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHVegan";
cat.haircut = "Bald:100";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticNMRIHWally";
cat.haircut = "Recede:100";
cat.beard = "Goatee:100";
cat.haircutColor = "0.60,0.46,0.30:100"; -- Duller Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticPostalDude";
cat.haircut = "Messy:100";
cat.beard = "Chin:100";
cat.haircutColor = "0.82,0.71,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticRickGrimes";
cat.haircut = "Messy:100";
cat.beard = "Full:100";
cat.haircutColor = "0.60,0.46,0.30:100"; -- Duller Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticRochelle";
cat.haircut = "Back:100";
cat.beard = "None:100";
cat.haircutColor = "0.10,0.01,0.05:100" -- Black
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticSamRivot";
cat.haircut = "Short:100";
cat.beard = "Full:100";
cat.haircutColor = "0.50,0.50,0.50:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticShaunoftheDead";
cat.haircut = "Messy:100";
cat.beard = "None:100";
cat.haircutColor = "0.99,0.92,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticSexyNurse";
cat.haircut = "Long2:100";
cat.beard = "None:100";
cat.haircutColor = "0.99,0.92,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticSexyBunny";
cat.haircut = "Hat:5;OverEye:5;Bun:6;Back:6;Long:6;Kate:5;Long2:6;Ponytail:6;Longcurly:5;Long2curly:6;BobCurly:5;KateCurly:6;OverEyeCurly:5;RachelCurly:5;Rachel:6;CentrePartingLong:5;Grungey:6;GrungeyParted:6";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticTF2SpyBlue";
cat.haircut = "Bald:50;Short:50";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticTF2SpyRed";
cat.haircut = "Bald:50;Short:50";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticTheyLive";
cat.haircut = "Mullet:100";
cat.beard = "None:100";
cat.haircutColor = "0.82,0.71,0.55:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticTravelingBand";
cat.haircut = "LibertySpikes:7;MohawkFan:10;MohawkShort:10;MohawkSpike:7";
cat.haircutColor = "0.98,0.87,0:10;0.82,0.15,0.07:10;0.21,0.6,0.3:10;0.26,0.6,0.81:10";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticUncleSam";
cat.haircut = "Short:100";
cat.beard = "BeardOnly:100";
cat.haircutColor = "0.80,0.80,0.80:100"; --grey/white
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticWaldo";
cat.haircut = "Short:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"; --Brown
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticWinslow";
cat.haircut = "Bald:100";
cat.beard = "None:100";
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);
local cat = {};
cat.outfit = "AuthenticZoey";
cat.haircut = "Ponytail:100";
cat.beard = "None:100";
cat.haircutColor = "0.33,0.16,0.16:100"
table.insert(HairOutfitDefinitions.haircutOutfitDefinition, cat);