-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["industry_tk_02_25"] = {{ name = "other", tiles = {"container_overlays_tk_01_0", "container_overlays_tk_01_0"} }}
overlayMap["industry_tk_02_26"] = {{ name = "other", tiles = {"container_overlays_tk_01_1", "container_overlays_tk_01_1"} }}
overlayMap["trash_containers_tk_01_2"] = {{ name = "other", tiles = {"container_overlays_tk_02_25", "container_overlays_tk_02_24"} }}
overlayMap["trash_containers_tk_01_3"] = {{ name = "other", tiles = {"container_overlays_tk_02_27", "container_overlays_tk_02_26"} }}
overlayMap["trash_containers_tk_01_4"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_33", "container_overlays_tk_02_32"} }, { name = "other", tiles = {"container_overlays_tk_02_36", "container_overlays_tk_02_36"} }}
overlayMap["trash_containers_tk_01_5"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_35", "container_overlays_tk_02_34"} }, { name = "other", tiles = {"container_overlays_tk_02_37", "container_overlays_tk_02_37"} }}
overlayMap["trash_containers_tk_01_6"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_33", "container_overlays_tk_02_32"} }, { name = "other", tiles = {"container_overlays_tk_02_36", "container_overlays_tk_02_36"} }}
overlayMap["trash_containers_tk_01_7"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_35", "container_overlays_tk_02_34"} }, { name = "other", tiles = {"container_overlays_tk_02_37", "container_overlays_tk_02_37"} }}
overlayMap["trash_containers_tk_01_8"] = {{ name = "other", tiles = {"container_overlays_tk_02_9", "container_overlays_tk_02_8"} }}
overlayMap["trash_containers_tk_01_9"] = {{ name = "other", tiles = {"container_overlays_tk_02_11", "container_overlays_tk_02_10"} }}
overlayMap["trash_containers_tk_01_16"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_17"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_18"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_19"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_20"] = {{ name = "other", tiles = {"container_overlays_tk_02_20", "container_overlays_tk_02_4"} }}
overlayMap["trash_containers_tk_01_21"] = {{ name = "other", tiles = {"container_overlays_tk_02_21", "container_overlays_tk_02_5"} }}
overlayMap["trash_containers_tk_01_22"] = {{ name = "other", tiles = {"container_overlays_tk_02_22", "container_overlays_tk_02_6"} }}
overlayMap["trash_containers_tk_01_23"] = {{ name = "other", tiles = {"container_overlays_tk_02_23", "container_overlays_tk_02_7"} }}
overlayMap["trash_containers_tk_01_24"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_25"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_26"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_27"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_28"] = {{ name = "other", tiles = {"container_overlays_tk_02_28", "container_overlays_tk_02_12"} }}
overlayMap["trash_containers_tk_01_29"] = {{ name = "other", tiles = {"container_overlays_tk_02_29", "container_overlays_tk_02_13"} }}
overlayMap["trash_containers_tk_01_30"] = {{ name = "other", tiles = {"container_overlays_tk_02_30", "container_overlays_tk_02_14"} }}
overlayMap["trash_containers_tk_01_31"] = {{ name = "other", tiles = {"container_overlays_tk_02_31", "container_overlays_tk_02_15"} }}
overlayMap["trash_containers_tk_01_40"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_41"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_42"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_43"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_44"] = {{ name = "other", tiles = {"container_overlays_tk_02_20", "container_overlays_tk_02_4"} }}
overlayMap["trash_containers_tk_01_45"] = {{ name = "other", tiles = {"container_overlays_tk_02_21", "container_overlays_tk_02_5"} }}
overlayMap["trash_containers_tk_01_46"] = {{ name = "other", tiles = {"container_overlays_tk_02_22", "container_overlays_tk_02_6"} }}
overlayMap["trash_containers_tk_01_47"] = {{ name = "other", tiles = {"container_overlays_tk_02_23", "container_overlays_tk_02_7"} }}
overlayMap["trash_containers_tk_01_48"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_49"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_50"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_51"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_52"] = {{ name = "other", tiles = {"container_overlays_tk_02_28", "container_overlays_tk_02_12"} }}
overlayMap["trash_containers_tk_01_53"] = {{ name = "other", tiles = {"container_overlays_tk_02_29", "container_overlays_tk_02_13"} }}
overlayMap["trash_containers_tk_01_54"] = {{ name = "other", tiles = {"container_overlays_tk_02_30", "container_overlays_tk_02_14"} }}
overlayMap["trash_containers_tk_01_55"] = {{ name = "other", tiles = {"container_overlays_tk_02_31", "container_overlays_tk_02_15"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
