Distributions = Distributions or {};

local distributionTable = {
    
   armysurplus = {
        isShop = true,
        shelves = {
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,			
				"Base.Suit_Chempak", 	2,			
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,						
            },
        },
        
        metal_shelves = {
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,			
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
        },
        
        
        clothingrack = {
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,			
				"Base.Suit_Chempak", 	2,				
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
        },
    },
	
    gunstore = {
        isShop = true,
        counter ={
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,			
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
            dontSpawnAmmo = true,
        },
        
        displaycase ={
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,				
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
            dontSpawnAmmo = true,
        },
        
        locker ={
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,			
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
            dontSpawnAmmo = true,
        },
        
        metal_shelves ={
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,				
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
            dontSpawnAmmo = true,
        },
    },
    
    gunstorestorage ={
        isShop = true,
        all={
            rolls = 3,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,				
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
            
            dontSpawnAmmo = true,
        },
    },	
	
    policestorage = {
		locker = {
			rolls = 4,
			items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,			
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
        },
        
        metal_shelves =
        {
            rolls = 4,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,			
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            }
        },
    },
    
    armystorage = {
        locker ={
            rolls = 2,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,	
				"Base.Suit_Chempak", 	2,			
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            },
        },
        
        metal_shelves =
        {
            rolls = 2,
            items = {
				"Base.Ela_Jacket", 	2,
				"Base.Ela_Pants", 	2,	
				"Base.Gorka_Jacket", 	2,
				"Base.Gorka_Jacket2", 	2,
				"Base.Gorka_Jacket3", 	2,			
				"Base.Gorka_Pants", 	2,		
				"Base.Gorka_Pants2", 	2,		
				"Base.Gorka_Pants3", 	2,	
				"Base.Hat_FAST_Opscore", 	2,				
				"Base.Hat_M1_Helmet", 	2,		
				"Base.Hat_M1_Helmet_Ori", 	2,	
				"Base.Hat_Maska", 	2,				
				"Base.Hat_Gentex_Helmet", 	2,					
				"Base.Hat_Face_Shield", 	2,				
				"Base.Hat_Helmet_Headset", 	2,		
				"Base.Hat_Maska_Visor", 	2,				
				"Base.Hat_Maska_Visor2", 	2,						
				"Base.Hat_Ela_Hat", 	2,
				"Base.Hat_Ela_Hat_Only", 	2,				
				"Base.Hat_Beret_Tactical_Only", 	2,					
				"Base.Hat_MCU_GasMask", 	2,	
				"Base.Hat_M45_GasMask", 	2,					
				"Base.Hat_FM53", 	2,					
				"Base.Hat_M50", 	2,						
				"Base.Bag_Sniper_Pack", 	2,	
				"Base.Bag_ARVN_Rucksack", 	2,		
				"Base.Bag_ST53_Set", 	2,	
				"Base.Bag_Tactical_Belt_Front", 	2,			
				"Base.Glasses_X1000", 	2,	
				"Base.Glasses_Napier", 	2,					
				"Base.Glasses_Crewman_Goggles", 	2,					
				"Base.Hat_Sordin", 	2,					
				"Base.Hat_Astrocom", 	2,						
				"Base.Bag_D3M", 	2,	
				"Base.Bag_Smersh_Vest", 	2,				
				"Base.Hat_Sam_NV", 	2,		
				"Base.Hat_PVS15_ON", 	2,		
				"Base.Hat_NV18_ON", 	2,			
				"Base.Armor_Defender", 	2,
				"Base.Bag_Plate_Carrier", 	2,		
				"Base.Bag_Sniper_Hood", 	2,		
				"Base.Suit_Chempak", 	2,		
				"Base.Killa_Jacket", 	2,		
				"Base.Killa_Pants", 	2,							
				"Base.Hat_Killa", 	2,								
				"Base.Hat_Killa_Visor", 	2,				
				"Base.Armor_6B13", 	2,					
				"Base.Bag_Blackhawk", 	2,					
				"Base.Bag_Duty_Belt_Front", 	2,				
				"Base.Bag_ZIP", 	2,		
				"Base.Bag_SSO", 	2,		
				"Base.Bag_Savotta", 	2,		
				"Base.Bag_Bush", 	2,		
				"Base.Bag_Hunting", 	2,	
				"Base.Bag_Radio_Pack", 	2,							
            }
        },
    },	
}

table.insert(Distributions, 1, distributionTable);

--for mod compat:
	