--***********************************************************
--**                    THE INDIE STONE                    **
--***********************************************************

local group = AttachedLocations.getGroup("Human")
group:getOrCreateLocation("Balloon Left"):setAttachmentName("Bip01_L_Shoulder")
group:getOrCreateLocation("Balloon Right"):setAttachmentName("Bip01_R_Shoulder")
group:getOrCreateLocation("Balloon Center"):setAttachmentName("Neck_Balloon")
group:getOrCreateLocation("Canteen Left"):setAttachmentName("Canteen_L")
group:getOrCreateLocation("Canteen Right"):setAttachmentName("Canteen_R")
group:getOrCreateLocation("Item Slot 2"):setAttachmentName("Pills_R")
group:getOrCreateLocation("Item Slot 1"):setAttachmentName("Pills_L")
group:getOrCreateLocation("Pills Right"):setAttachmentName("Pills_R")
group:getOrCreateLocation("Pills Left"):setAttachmentName("Pills_L")
group:getOrCreateLocation("Pipe Waist"):setAttachmentName("Pipe_Waist")
group:getOrCreateLocation("Left Hand"):setAttachmentName("Bip01_L_Finger1")
group:getOrCreateLocation("Left Hand Item"):setAttachmentName("stop_sign_left")
group:getOrCreateLocation("Right Hand"):setAttachmentName("Bip01_R_Finger0")
group:getOrCreateLocation("Right Hand1"):setAttachmentName("Bip01_R_Finger1")
group:getOrCreateLocation("Right Hand Item"):setAttachmentName("stop_sign_right")
group:getOrCreateLocation("BucketHead"):setAttachmentName("Bip01_Head")
group:getOrCreateLocation("MinerLight"):setAttachmentName("knife_head")
group:getOrCreateLocation("Military Flashlight Left"):setAttachmentName("MilitaryFlashlight_L")
group:getOrCreateLocation("Military Flashlight Right"):setAttachmentName("MilitaryFlashlight_R")
group:getOrCreateLocation("Nightstick Left"):setAttachmentName("nightstick_left")
group:getOrCreateLocation("Paper Left"):setAttachmentName("Paper_left")
group:getOrCreateLocation("Paper Right"):setAttachmentName("Paper_right")
group:getOrCreateLocation("WalkieTalkie Left"):setAttachmentName("WalkieTalkie_L")
group:getOrCreateLocation("WalkieTalkie Right"):setAttachmentName("WalkieTalkie_R")
group:getOrCreateLocation("CherryLeg"):setAttachmentName("Cherry_Leg_R")

-- Backpack attachments --
group:getOrCreateLocation("Flare Gun Left"):setAttachmentName("BackPack_Flare_Left")
group:getOrCreateLocation("Flare Gun Right"):setAttachmentName("BackPack_Flare_Right")

group:getOrCreateLocation("Schoolbag Plasticbag Bag"):setAttachmentName("BackpackSecondary_SchoolbagPlasticBag")
group:getOrCreateLocation("Schoolbag Garbage Bag"):setAttachmentName("BackpackSecondary_SchoolbagGarbageBag")
group:getOrCreateLocation("Schoolbag Tote Bag"):setAttachmentName("BackpackSecondary_SchoolbagToteBag")
group:getOrCreateLocation("Schoolbag Purse"):setAttachmentName("BackpackSecondary_SchoolbagPurse")
group:getOrCreateLocation("Schoolbag EmptySandbag"):setAttachmentName("BackpackSecondary_SchoolbagEmptySandbag")
group:getOrCreateLocation("Schoolbag Seedbag"):setAttachmentName("BackpackSecondary_SchoolbagSeedbag")
group:getOrCreateLocation("Schoolbag Handbag"):setAttachmentName("BackpackSecondary_SchoolbagHandbag")
group:getOrCreateLocation("Schoolbag Toolbox"):setAttachmentName("BackpackSecondary_SchoolbagToolbox")
group:getOrCreateLocation("Schoolbag FirstAidKit"):setAttachmentName("BackpackSecondary_SchoolbagFirstAidKit")
group:getOrCreateLocation("Schoolbag Bag_L4DeadMedkit"):setAttachmentName("BackpackSecondary_SchoolbagBag_L4DeadMedkit")
group:getOrCreateLocation("Schoolbag Lunchbox"):setAttachmentName("BackpackSecondary_SchoolbagLunchbox")
group:getOrCreateLocation("Schoolbag PistolCase"):setAttachmentName("BackpackSecondary_SchoolbagPistolCase")

group:getOrCreateLocation("Schoolbag Rope Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Rope")
group:getOrCreateLocation("Schoolbag FlareGun Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_FlareGun")
group:getOrCreateLocation("Schoolbag Explosive Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Explosive")
group:getOrCreateLocation("Schoolbag AuthenticExplosive Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_AuthenticExplosive")
group:getOrCreateLocation("Schoolbag GasMask Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_GasMask")
group:getOrCreateLocation("Schoolbag Walkie Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Walkie")
group:getOrCreateLocation("Schoolbag SheetRope Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_SheetRope")
group:getOrCreateLocation("Schoolbag Hammer Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Hammer")
group:getOrCreateLocation("Schoolbag Screwdriver Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Screwdriver")
group:getOrCreateLocation("Schoolbag Knife Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Knife")
group:getOrCreateLocation("Schoolbag Saucepan Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Saucepan")
group:getOrCreateLocation("Schoolbag Pan Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Pan")
group:getOrCreateLocation("Schoolbag Wrench Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_Wrench")
group:getOrCreateLocation("Schoolbag MeatCleaver Slot 1"):setAttachmentName("BackPack_Schoolbag_Tier1Item_MeatCleaver")

group:getOrCreateLocation("Schoolbag Rope Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Rope")
group:getOrCreateLocation("Schoolbag FlareGun Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_FlareGun")
group:getOrCreateLocation("Schoolbag Explosive Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Explosive")
group:getOrCreateLocation("Schoolbag AuthenticExplosive Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_AuthenticExplosive")
group:getOrCreateLocation("Schoolbag GasMask Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_GasMask")
group:getOrCreateLocation("Schoolbag Walkie Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Walkie")
group:getOrCreateLocation("Schoolbag SheetRope Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_SheetRope")
group:getOrCreateLocation("Schoolbag Hammer Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Hammer")
group:getOrCreateLocation("Schoolbag Screwdriver Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Screwdriver")
group:getOrCreateLocation("Schoolbag Knife Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Knife")
group:getOrCreateLocation("Schoolbag Saucepan Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Saucepan")
group:getOrCreateLocation("Schoolbag Pan Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Pan")
group:getOrCreateLocation("Schoolbag Wrench Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_Wrench")
group:getOrCreateLocation("Schoolbag MeatCleaver Slot 2"):setAttachmentName("BackPack_Schoolbag_Tier2Item_MeatCleaver")


group:getOrCreateLocation("Schoolbag Rope Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Rope")
group:getOrCreateLocation("Schoolbag FlareGun Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_FlareGun")
group:getOrCreateLocation("Schoolbag Explosive Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Explosive")
group:getOrCreateLocation("Schoolbag AuthenticExplosive Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_AuthenticExplosive")
group:getOrCreateLocation("Schoolbag GasMask Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_GasMask")
group:getOrCreateLocation("Schoolbag Walkie Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Walkie")
group:getOrCreateLocation("Schoolbag SheetRope Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_SheetRope")
group:getOrCreateLocation("Schoolbag Hammer Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Hammer")
group:getOrCreateLocation("Schoolbag Screwdriver Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Screwdriver")
group:getOrCreateLocation("Schoolbag Knife Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Knife")
group:getOrCreateLocation("Schoolbag Saucepan Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Saucepan")
group:getOrCreateLocation("Schoolbag Pan Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Pan")
group:getOrCreateLocation("Schoolbag Wrench Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_Wrench")
group:getOrCreateLocation("Schoolbag MeatCleaver Slot 3"):setAttachmentName("BackPack_Schoolbag_Tier3Item_MeatCleaver")

group:getOrCreateLocation("Schoolbag Waterbottle Right"):setAttachmentName("BackPack_Schoolbag_Waterbottle_Right")
group:getOrCreateLocation("Schoolbag Canteen Right"):setAttachmentName("BackPack_Schoolbag_Canteen_Right")
group:getOrCreateLocation("Schoolbag Sodacan Right"):setAttachmentName("BackPack_Schoolbag_Sodacan_Right")
group:getOrCreateLocation("Schoolbag Waterbottle Left"):setAttachmentName("BackPack_Schoolbag_Waterbottle_Left")
group:getOrCreateLocation("Schoolbag Canteen Left"):setAttachmentName("BackPack_Schoolbag_Canteen_Left")
group:getOrCreateLocation("Schoolbag Sodacan Left"):setAttachmentName("BackPack_Schoolbag_Sodacan_Left")

group:getOrCreateLocation("Schoolbag Plushie Spiffo"):setAttachmentName("BackPack_Schoolbag_PlushieSpiffo")
group:getOrCreateLocation("Schoolbag Plushie Doll"):setAttachmentName("BackPack_Schoolbag_PlushieDoll")
group:getOrCreateLocation("Schoolbag Plushie TeddyBear"):setAttachmentName("BackPack_Schoolbag_PlushieTeddyBear")
group:getOrCreateLocation("Schoolbag Umbrella Left"):setAttachmentName("BackPack_Schoolbag_Umbrella")
group:getOrCreateLocation("Schoolbag Military Flashlight"):setAttachmentName("BackPack_Schoolbag_Flashlight")
group:getOrCreateLocation("Schoolbag Balloon Left"):setAttachmentName("BackPack_Schoolbag_L_Balloon")
group:getOrCreateLocation("Schoolbag Balloon Right"):setAttachmentName("BackPack_Schoolbag_R_Balloon")


group:getOrCreateLocation("Dufflebag Plasticbag Bag"):setAttachmentName("BackpackSecondary_DufflebagPlasticBag")
group:getOrCreateLocation("Dufflebag Garbage Bag"):setAttachmentName("BackpackSecondary_DufflebagGarbageBag")
group:getOrCreateLocation("Dufflebag Tote Bag"):setAttachmentName("BackpackSecondary_DufflebagToteBag")
group:getOrCreateLocation("Dufflebag Purse"):setAttachmentName("BackpackSecondary_DufflebagPurse")
group:getOrCreateLocation("Dufflebag EmptySandbag"):setAttachmentName("BackpackSecondary_DufflebagEmptySandbag")
group:getOrCreateLocation("Dufflebag Seedbag"):setAttachmentName("BackpackSecondary_DufflebagSeedbag")
group:getOrCreateLocation("Dufflebag Handbag"):setAttachmentName("BackpackSecondary_DufflebagHandbag")
group:getOrCreateLocation("Dufflebag Toolbox"):setAttachmentName("BackpackSecondary_DufflebagToolbox")
group:getOrCreateLocation("Dufflebag FirstAidKit"):setAttachmentName("BackpackSecondary_DufflebagFirstAidKit")
group:getOrCreateLocation("Dufflebag Bag_L4DeadMedkit"):setAttachmentName("BackpackSecondary_DufflebagBag_L4DeadMedkit")
group:getOrCreateLocation("Dufflebag Lunchbox"):setAttachmentName("BackpackSecondary_DufflebagLunchbox")
group:getOrCreateLocation("Dufflebag PistolCase"):setAttachmentName("BackpackSecondary_DufflebagPistolCase")

group:getOrCreateLocation("Dufflebag Rope Slot 1"):setAttachmentName("BackPack_Dufflebag_Tier1Item_Rope")
group:getOrCreateLocation("Dufflebag FlareGun Slot 1"):setAttachmentName("BackPack_Dufflebag_Tier1Item_FlareGun")
group:getOrCreateLocation("Dufflebag Explosive Slot 1"):setAttachmentName("BackPack_Dufflebag_Tier1Item_Explosive")
group:getOrCreateLocation("Dufflebag AuthenticExplosive Slot 1"):setAttachmentName("BackPack_Dufflebag_Tier1Item_AuthenticExplosive")
group:getOrCreateLocation("Dufflebag GasMask Slot 1"):setAttachmentName("BackPack_Dufflebag_Tier1Item_GasMask")
group:getOrCreateLocation("Dufflebag Walkie Slot 1"):setAttachmentName("BackPack_Dufflebag_Tier1Item_Walkie")

group:getOrCreateLocation("Dufflebag Rope Slot 2"):setAttachmentName("BackPack_Dufflebag_Tier2Item_Rope")
group:getOrCreateLocation("Dufflebag FlareGun Slot 2"):setAttachmentName("BackPack_Dufflebag_Tier2tem_FlareGun")
group:getOrCreateLocation("Dufflebag Explosive Slot 2"):setAttachmentName("BackPack_Dufflebag_Tier2Item_Explosive")
group:getOrCreateLocation("Dufflebag AuthenticExplosive Slot 2"):setAttachmentName("BackPack_Dufflebag_Tier2Item_AuthenticExplosive")
group:getOrCreateLocation("Dufflebag GasMask Slot 2"):setAttachmentName("BackPack_Dufflebag_Tier2Item_GasMask")
group:getOrCreateLocation("Dufflebag Walkie Slot 2"):setAttachmentName("BackPack_Dufflebag_Tier2Item_Walkie")

group:getOrCreateLocation("Dufflebag Rope Slot 3"):setAttachmentName("BackPack_Dufflebag_Tier3Item_Rope")
group:getOrCreateLocation("Dufflebag FlareGun Slot 3"):setAttachmentName("BackPack_Dufflebag_Tier3Item_FlareGun")
group:getOrCreateLocation("Dufflebag Explosive Slot 3"):setAttachmentName("BackPack_Dufflebag_Tier3Item_Explosive")
group:getOrCreateLocation("Dufflebag AuthenticExplosive Slot 3"):setAttachmentName("BackPack_Dufflebag_Tier3Item_AuthenticExplosive")
group:getOrCreateLocation("Dufflebag GasMask Slot 3"):setAttachmentName("BackPack_Dufflebag_Tier3Item_GasMask")
group:getOrCreateLocation("Dufflebag Walkie Slot 3"):setAttachmentName("BackPack_Dufflebag_Tier3Item_Walkie")

group:getOrCreateLocation("Dufflebag Waterbottle Right"):setAttachmentName("BackPack_Dufflebag_Waterbottle_Right")
group:getOrCreateLocation("Dufflebag Canteen Right"):setAttachmentName("BackPack_Dufflebag_Canteen_Right")
group:getOrCreateLocation("Dufflebag Sodacan Right"):setAttachmentName("BackPack_Dufflebag_Sodacan_Right")

group:getOrCreateLocation("Dufflebag Plushie Spiffo"):setAttachmentName("BackPack_Dufflebag_PlushieSpiffo")
group:getOrCreateLocation("Dufflebag Plushie Doll"):setAttachmentName("BackPack_Dufflebag_PlushieDoll")
group:getOrCreateLocation("Dufflebag Plushie TeddyBear"):setAttachmentName("BackPack_Dufflebag_PlushieTeddyBear")
group:getOrCreateLocation("Dufflebag Umbrella Right"):setAttachmentName("BackPack_Dufflebag_Umbrella")
group:getOrCreateLocation("Dufflebag Military Flashlight"):setAttachmentName("BackPack_Dufflebag_Flashlight")
group:getOrCreateLocation("Dufflebag Saw Right"):setAttachmentName("BackPack_Dufflebag_Saw")
group:getOrCreateLocation("Dufflebag Balloon Left"):setAttachmentName("BackPack_Dufflebag_L_Balloon")
group:getOrCreateLocation("Dufflebag Balloon Right"):setAttachmentName("BackPack_Dufflebag_R_Balloon")

group:getOrCreateLocation("HikingBag Plasticbag Bag"):setAttachmentName("BackpackSecondary_HikingbagPlasticBag")
group:getOrCreateLocation("HikingBag Garbage Bag"):setAttachmentName("BackpackSecondary_HikingbagGarbageBag")
group:getOrCreateLocation("HikingBag Tote Bag"):setAttachmentName("BackpackSecondary_HikingbagToteBag")
group:getOrCreateLocation("HikingBag Purse"):setAttachmentName("BackpackSecondary_HikingbagPurse")
group:getOrCreateLocation("HikingBag EmptySandbag"):setAttachmentName("BackpackSecondary_HikingbagEmptySandbag")
group:getOrCreateLocation("HikingBag Seedbag"):setAttachmentName("BackpackSecondary_HikingbagSeedbag")
group:getOrCreateLocation("HikingBag Handbag"):setAttachmentName("BackpackSecondary_HikingbagHandbag")
group:getOrCreateLocation("HikingBag Toolbox"):setAttachmentName("BackpackSecondary_HikingbagToolbox")
group:getOrCreateLocation("HikingBag FirstAidKit"):setAttachmentName("BackpackSecondary_HikingbagFirstAidKit")
group:getOrCreateLocation("HikingBag Bag_L4DeadMedkit"):setAttachmentName("BackpackSecondary_HikingbagBag_L4DeadMedkit")
group:getOrCreateLocation("HikingBag Lunchbox"):setAttachmentName("BackpackSecondary_HikingbagLunchbox")
group:getOrCreateLocation("HikingBag PistolCase"):setAttachmentName("BackpackSecondary_HikingbagPistolCase")

group:getOrCreateLocation("HikingBag Rope Slot 1"):setAttachmentName("BackPack_Hikingbag_Tier1Item_Rope")
group:getOrCreateLocation("HikingBag FlareGun Slot 1"):setAttachmentName("BackPack_Hikingbag_Tier1Item_FlareGun")
group:getOrCreateLocation("HikingBag Explosive Slot 1"):setAttachmentName("BackPack_Hikingbag_Tier1Item_Explosive")
group:getOrCreateLocation("HikingBag AuthenticExplosive Slot 1"):setAttachmentName("BackPack_Hikingbag_Tier1Item_AuthenticExplosive")
group:getOrCreateLocation("HikingBag GasMask Slot 1"):setAttachmentName("BackPack_Hikingbag_Tier1Item_GasMask")
group:getOrCreateLocation("HikingBag Walkie Slot 1"):setAttachmentName("BackPack_Hikingbag_Tier1Item_Walkie")

group:getOrCreateLocation("HikingBag Rope Slot 2"):setAttachmentName("BackPack_Hikingbag_Tier2Item_Rope")
group:getOrCreateLocation("HikingBag FlareGun Slot 2"):setAttachmentName("BackPack_Hikingbag_Tier2Item_FlareGun")
group:getOrCreateLocation("HikingBag Explosive Slot 2"):setAttachmentName("BackPack_Hikingbag_Tier2Item_Explosive")
group:getOrCreateLocation("HikingBag AuthenticExplosive Slot 2"):setAttachmentName("BackPack_Hikingbag_Tier2Item_AuthenticExplosive")
group:getOrCreateLocation("HikingBag GasMask Slot 2"):setAttachmentName("BackPack_Hikingbag_Tier2Item_GasMask")
group:getOrCreateLocation("HikingBag Walkie Slot 2"):setAttachmentName("BackPack_Hikingbag_Tier2Item_Walkie")

group:getOrCreateLocation("HikingBag Rope Slot 3"):setAttachmentName("BackPack_Hikingbag_Tier3Item_Rope")
group:getOrCreateLocation("HikingBag FlareGun Slot 3"):setAttachmentName("BackPack_Hikingbag_Tier3Item_FlareGun")
group:getOrCreateLocation("HikingBag Explosive Slot 3"):setAttachmentName("BackPack_Hikingbag_Tier3Item_Explosive")
group:getOrCreateLocation("HikingBag AuthenticExplosive Slot 3"):setAttachmentName("BackPack_Hikingbag_Tier3Item_AuthenticExplosive")
group:getOrCreateLocation("HikingBag GasMask Slot 3"):setAttachmentName("BackPack_HikingBag_Tier3Item_GasMask")
group:getOrCreateLocation("HikingBag Walkie Slot 3"):setAttachmentName("BackPack_Hikingbag_Tier3Item_Walkie")

group:getOrCreateLocation("HikingBag Waterbottle Left"):setAttachmentName("BackPack_Hikingbag_Waterbottle_Left")
group:getOrCreateLocation("HikingBag Canteen Left"):setAttachmentName("BackPack_Hikingbag_Canteen_Left")
group:getOrCreateLocation("HikingBag Sodacan Left"):setAttachmentName("BackPack_Hikingbag_Sodacan_Left")
group:getOrCreateLocation("HikingBag Waterbottle Right"):setAttachmentName("BackPack_Hikingbag_Waterbottle_Right")
group:getOrCreateLocation("HikingBag Canteen Right"):setAttachmentName("BackPack_Hikingbag_Canteen_Right")
group:getOrCreateLocation("HikingBag Sodacan Right"):setAttachmentName("BackPack_Hikingbag_Sodacan_Right")

group:getOrCreateLocation("HikingBag Plushie Spiffo"):setAttachmentName("BackPack_Hikingbag_PlushieSpiffo")
group:getOrCreateLocation("HikingBag Plushie Doll"):setAttachmentName("BackPack_Hikingbag_PlushieDoll")
group:getOrCreateLocation("HikingBag Plushie TeddyBear"):setAttachmentName("BackPack_Hikingbag_PlushieTeddyBear")
group:getOrCreateLocation("HikingBag Umbrella Left"):setAttachmentName("BackPack_Hikingbag_Umbrella")
group:getOrCreateLocation("HikingBag Military Flashlight"):setAttachmentName("BackPack_Hikingbag_Flashlight")
group:getOrCreateLocation("HikingBag Balloon Left"):setAttachmentName("BackPack_Hikingbag_L_Balloon")
group:getOrCreateLocation("HikingBag Balloon Right"):setAttachmentName("BackPack_Hikingbag_R_Balloon")

group:getOrCreateLocation("BigHikingBag Plasticbag Bag"):setAttachmentName("BackpackSecondary_BigHikingBagPlasticBag")
group:getOrCreateLocation("BigHikingBag Garbage Bag"):setAttachmentName("BackpackSecondary_BigHikingBagGarbageBag")
group:getOrCreateLocation("BigHikingBag Tote Bag"):setAttachmentName("BackpackSecondary_BigHikingBagToteBag")
group:getOrCreateLocation("BigHikingBag Purse"):setAttachmentName("BackpackSecondary_BigHikingBagPurse")
group:getOrCreateLocation("BigHikingBag EmptySandbag"):setAttachmentName("BackpackSecondary_BigHikingBagEmptySandbag")
group:getOrCreateLocation("BigHikingBag Seedbag"):setAttachmentName("BackpackSecondary_BigHikingbagSeedbag")
group:getOrCreateLocation("BigHikingBag Handbag"):setAttachmentName("BackpackSecondary_BigHikingBagHandbag")
group:getOrCreateLocation("BigHikingBag Toolbox"):setAttachmentName("BackpackSecondary_BigHikingBagToolbox")
group:getOrCreateLocation("BigHikingBag FirstAidKit"):setAttachmentName("BackpackSecondary_BigHikingBagFirstAidKit")
group:getOrCreateLocation("BigHikingBag Bag_L4DeadMedkit"):setAttachmentName("BackpackSecondary_BigHikingBagBag_L4DeadMedkit")
group:getOrCreateLocation("BigHikingBag Lunchbox"):setAttachmentName("BackpackSecondary_BigHikingBagLunchbox")
group:getOrCreateLocation("BigHikingBag PistolCase"):setAttachmentName("BackpackSecondary_BigHikingBagLunchbox")

group:getOrCreateLocation("BigHikingBag Rope Slot 1"):setAttachmentName("BackPack_BigHikingBag_Tier1Item_Rope")
group:getOrCreateLocation("BigHikingBag FlareGun Slot 1"):setAttachmentName("BackPack_BigHikingBag_Tier1Item_FlareGun")
group:getOrCreateLocation("BigHikingBag Explosive Slot 1"):setAttachmentName("BackPack_BigHikingBag_Tier1Item_Explosive")
group:getOrCreateLocation("BigHikingBag AuthenticExplosive Slot 1"):setAttachmentName("BackPack_BigHikingBag_Tier1Item_AuthenticExplosive")
group:getOrCreateLocation("BigHikingBag GasMask Slot 1"):setAttachmentName("BackPack_BigHikingBag_Tier1Item_GasMask")
group:getOrCreateLocation("BigHikingBag Walkie Slot 1"):setAttachmentName("BackPack_BigHikingBag_Tier1Item_Walkie")

group:getOrCreateLocation("BigHikingBag Rope Slot 2"):setAttachmentName("BackPack_BigHikingBag_Tier2Item_Rope")
group:getOrCreateLocation("BigHikingBag FlareGun Slot 2"):setAttachmentName("BackPack_BigHikingBag_Tier2Item_FlareGun")
group:getOrCreateLocation("BigHikingBag Explosive Slot 2"):setAttachmentName("BackPack_BigHikingBag_Tier2Item_Explosive")
group:getOrCreateLocation("BigHikingBag AuthenticExplosive Slot 2"):setAttachmentName("BackPack_BigHikingBag_Tier2Item_AuthenticExplosive")
group:getOrCreateLocation("BigHikingBag GasMask Slot 2"):setAttachmentName("BackPack_BigHikingBag_Tier2Item_GasMask")
group:getOrCreateLocation("BigHikingBag Walkie Slot 2"):setAttachmentName("BackPack_BigHikingBag_Tier2Item_Walkie")

group:getOrCreateLocation("BigHikingBag Rope Slot 3"):setAttachmentName("BackPack_BigHikingBag_Tier3Item_Rope")
group:getOrCreateLocation("BigHikingBag FlareGun Slot 3"):setAttachmentName("BackPack_BigHikingBag_Tier3Item_FlareGun")
group:getOrCreateLocation("BigHikingBag Explosive Slot 3"):setAttachmentName("BackPack_BigHikingBag_Tier3Item_Explosive")
group:getOrCreateLocation("BigHikingBag AuthenticExplosive Slot 3"):setAttachmentName("BackPack_BigHikingBag_Tier3Item_AuthenticExplosive")
group:getOrCreateLocation("BigHikingBag GasMask Slot 3"):setAttachmentName("BackPack_BigHikingBag_Tier3Item_GasMask")
group:getOrCreateLocation("BigHikingBag Walkie Slot 3"):setAttachmentName("BackPack_BigHikingBag_Tier3Item_Walkie")

group:getOrCreateLocation("BigHikingBag Rope Slot 4"):setAttachmentName("BackPack_BigHikingBag_Tier4Item_Rope")
group:getOrCreateLocation("BigHikingBag FlareGun Slot 4"):setAttachmentName("BackPack_BigHikingBag_Tier4Item_FlareGun")
group:getOrCreateLocation("BigHikingBag Explosive Slot 4"):setAttachmentName("BackPack_BigHikingBag_Tier4Item_Explosive")
group:getOrCreateLocation("BigHikingBag AuthenticExplosive Slot 4"):setAttachmentName("BackPack_BigHikingBag_Tier4Item_AuthenticExplosive")
group:getOrCreateLocation("BigHikingBag GasMask Slot 4"):setAttachmentName("BackPack_BigHikingBag_Tier4Item_GasMask")
group:getOrCreateLocation("BigHikingBag Walkie Slot 4"):setAttachmentName("BackPack_BigHikingBag_Tier4Item_Walkie")

group:getOrCreateLocation("BigHikingBag Waterbottle Left"):setAttachmentName("BackPack_BigHikingBag_Waterbottle_Left")
group:getOrCreateLocation("BigHikingBag Canteen Left"):setAttachmentName("BackPack_BigHikingBag_Canteen_Left")
group:getOrCreateLocation("BigHikingBag Sodacan Left"):setAttachmentName("BackPack_BigHikingBag_Sodacan_Left")
group:getOrCreateLocation("BigHikingBag Waterbottle Right"):setAttachmentName("BackPack_BigHikingBag_Waterbottle_Right")
group:getOrCreateLocation("BigHikingBag Canteen Right"):setAttachmentName("BackPack_BigHikingBag_Canteen_Right")
group:getOrCreateLocation("BigHikingBag Sodacan Right"):setAttachmentName("BackPack_BigHikingBag_Sodacan_Right")

group:getOrCreateLocation("BigHikingBag Plushie Spiffo"):setAttachmentName("BackPack_BigHikingbag_PlushieSpiffo")
group:getOrCreateLocation("BigHikingBag Plushie Doll"):setAttachmentName("BackPack_BigHikingbag_PlushieDoll")
group:getOrCreateLocation("BigHikingBag Plushie TeddyBear"):setAttachmentName("BackPack_BigHikingbag_PlushieTeddyBear")
group:getOrCreateLocation("BigHikingBag Umbrella Right"):setAttachmentName("BackPack_BigHikingBag_Umbrella")
group:getOrCreateLocation("BigHikingBag Military Flashlight"):setAttachmentName("BackPack_BigHikingBag_Flashlight")
group:getOrCreateLocation("BigHikingBag Balloon Left"):setAttachmentName("BackPack_BigHikingBag_L_Balloon")
group:getOrCreateLocation("BigHikingBag Balloon Right"):setAttachmentName("BackPack_BigHikingBag_R_Balloon")

group:getOrCreateLocation("Alicepack Plasticbag Bag"):setAttachmentName("BackpackSecondary_AlicepackPlasticBag")
group:getOrCreateLocation("Alicepack Garbage Bag"):setAttachmentName("BackpackSecondary_AlicepackGarbageBag")
group:getOrCreateLocation("Alicepack Tote Bag"):setAttachmentName("BackpackSecondary_AlicepackToteBag")
group:getOrCreateLocation("Alicepack Purse"):setAttachmentName("BackpackSecondary_AlicepackPurse")
group:getOrCreateLocation("Alicepack EmptySandbag"):setAttachmentName("BackpackSecondary_AlicepackEmptySandbag")
group:getOrCreateLocation("Alicepack Seedbag"):setAttachmentName("BackpackSecondary_AlicepackSeedbag")
group:getOrCreateLocation("Alicepack Handbag"):setAttachmentName("BackpackSecondary_AlicepackHandbag")
group:getOrCreateLocation("Alicepack Toolbox"):setAttachmentName("BackpackSecondary_AlicepackToolbox")
group:getOrCreateLocation("Alicepack FirstAidKit"):setAttachmentName("BackpackSecondary_AlicepackFirstAidKit")
group:getOrCreateLocation("Alicepack Bag_L4DeadMedkit"):setAttachmentName("BackpackSecondary_AlicepackBag_L4DeadMedkit")
group:getOrCreateLocation("Alicepack Lunchbox"):setAttachmentName("BackpackSecondary_AlicepackLunchbox")
group:getOrCreateLocation("Alicepack PistolCase"):setAttachmentName("BackpackSecondary_AlicepackPistolCase")

group:getOrCreateLocation("Alicepack Rope Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_Rope")
group:getOrCreateLocation("Alicepack SheetRope Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_SheetRope")
group:getOrCreateLocation("Alicepack FlareGun Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_FlareGun")
group:getOrCreateLocation("Alicepack Explosive Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_Explosive")
group:getOrCreateLocation("Alicepack AuthenticExplosive Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_AuthenticExplosive")
group:getOrCreateLocation("Alicepack GasMask Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_GasMask")
group:getOrCreateLocation("Alicepack Walkie Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_Walkie")
group:getOrCreateLocation("Alicepack Hammer Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_Hammer")
group:getOrCreateLocation("Alicepack Screwdriver Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_Screwdriver")
group:getOrCreateLocation("Alicepack Knife Slot 1"):setAttachmentName("BackPack_Alicepack_Tier1Item_Knife")

group:getOrCreateLocation("Alicepack Rope Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_Rope")
group:getOrCreateLocation("Alicepack SheetRope Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_SheetRope")
group:getOrCreateLocation("Alicepack FlareGun Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_FlareGun")
group:getOrCreateLocation("Alicepack Explosive Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_Explosive")
group:getOrCreateLocation("Alicepack AuthenticExplosive Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_AuthenticExplosive")
group:getOrCreateLocation("Alicepack GasMask Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_GasMask")
group:getOrCreateLocation("Alicepack Hammer Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_Hammer")
group:getOrCreateLocation("Alicepack Screwdriver Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_Screwdriver")
group:getOrCreateLocation("Alicepack Knife Slot 2"):setAttachmentName("BackPack_Alicepack_Tier2Item_Knife")

group:getOrCreateLocation("Alicepack Rope Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_Rope")
group:getOrCreateLocation("Alicepack SheetRope Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_SheetRope")
group:getOrCreateLocation("Alicepack FlareGun Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_FlareGun")
group:getOrCreateLocation("Alicepack Explosive Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_Explosive")
group:getOrCreateLocation("Alicepack AuthenticExplosive Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_AuthenticExplosive")
group:getOrCreateLocation("Alicepack GasMask Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_GasMask")
group:getOrCreateLocation("Alicepack Walkie Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_Walkie")
group:getOrCreateLocation("Alicepack Hammer Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_Hammer")
group:getOrCreateLocation("Alicepack Screwdriver Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_Screwdriver")
group:getOrCreateLocation("Alicepack Knife Slot 3"):setAttachmentName("BackPack_Alicepack_Tier3Item_Knife")

group:getOrCreateLocation("Alicepack Rope Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_Rope")
group:getOrCreateLocation("Alicepack SheetRope Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_SheetRope")
group:getOrCreateLocation("Alicepack FlareGun Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_FlareGun")
group:getOrCreateLocation("Alicepack Explosive Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_Explosive")
group:getOrCreateLocation("Alicepack AuthenticExplosive Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_AuthenticExplosive")
group:getOrCreateLocation("Alicepack GasMask Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_GasMask")
group:getOrCreateLocation("Alicepack Walkie Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_Walkie")
group:getOrCreateLocation("Alicepack Hammer Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_Hammer")
group:getOrCreateLocation("Alicepack Screwdriver Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_Screwdriver")
group:getOrCreateLocation("Alicepack Knife Slot 4"):setAttachmentName("BackPack_Alicepack_Tier4Item_Knife")

group:getOrCreateLocation("Alicepack Rope Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_Rope")
group:getOrCreateLocation("Alicepack SheetRope Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_SheetRope")
group:getOrCreateLocation("Alicepack FlareGun Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_FlareGun")
group:getOrCreateLocation("Alicepack Explosive Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_Explosive")
group:getOrCreateLocation("Alicepack AuthenticExplosive Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_AuthenticExplosive")
group:getOrCreateLocation("Alicepack GasMask Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_GasMask")
group:getOrCreateLocation("Alicepack Walkie Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_Walkie")
group:getOrCreateLocation("Alicepack Hammer Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_Hammer")
group:getOrCreateLocation("Alicepack Screwdriver Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_Screwdriver")
group:getOrCreateLocation("Alicepack Knife Slot 5"):setAttachmentName("BackPack_Alicepack_Tier5Item_Knife")

group:getOrCreateLocation("Alicepack Waterbottle Right"):setAttachmentName("BackPack_Alicepack_Waterbottle_Right")
group:getOrCreateLocation("Alicepack Canteen Right"):setAttachmentName("BackPack_Alicepack_Canteen_Right")
group:getOrCreateLocation("Alicepack Sodacan Right"):setAttachmentName("BackPack_Alicepack_Sodacan_Right")
group:getOrCreateLocation("Alicepack Waterbottle Left"):setAttachmentName("BackPack_Alicepack_Waterbottle_Left")
group:getOrCreateLocation("Alicepack Canteen Left"):setAttachmentName("BackPack_Alicepack_Canteen_Left")
group:getOrCreateLocation("Alicepack Sodacan Left"):setAttachmentName("BackPack_Alicepack_Sodacan_Left")

group:getOrCreateLocation("Alicepack Plushie Spiffo"):setAttachmentName("BackPack_Alicepack_PlushieSpiffo")
group:getOrCreateLocation("Alicepack Plushie Doll"):setAttachmentName("BackPack_Alicepack_PlushieDoll")
group:getOrCreateLocation("Alicepack Plushie TeddyBear"):setAttachmentName("BackPack_Alicepack_PlushieTeddyBear")
group:getOrCreateLocation("Alicepack Umbrella Right"):setAttachmentName("BackPack_Alicepack_Umbrella")
group:getOrCreateLocation("Alicepack Military Flashlight"):setAttachmentName("BackPack_Alicepack_Flashlight")
group:getOrCreateLocation("Alicepack Balloon Left"):setAttachmentName("BackPack_Schoolbag_L_Balloon")
group:getOrCreateLocation("Alicepack Balloon Right"):setAttachmentName("BackPack_Schoolbag_R_Balloon")

-- Winslow attachments --
group:getOrCreateLocation("Spike Right"):setAttachmentName("Spike_right")
group:getOrCreateLocation("Spike Torso Left 1"):setAttachmentName("winslow_Torso_L_1")
group:getOrCreateLocation("Spike Torso Left 2"):setAttachmentName("winslow_Torso_L_2")
group:getOrCreateLocation("Spike Torso Left 3"):setAttachmentName("winslow_Torso_L_3")
group:getOrCreateLocation("Spike Torso Left 4"):setAttachmentName("winslow_Torso_L_4")
group:getOrCreateLocation("Spike Torso Left 5"):setAttachmentName("winslow_Torso_L_5")
group:getOrCreateLocation("Spike Torso Left 6"):setAttachmentName("winslow_Torso_L_6")
group:getOrCreateLocation("Spike Torso Right 1"):setAttachmentName("winslow_Torso_R_1")
group:getOrCreateLocation("Spike Torso Right 2"):setAttachmentName("winslow_Torso_R_2")
group:getOrCreateLocation("Spike Torso Right 3"):setAttachmentName("winslow_Torso_R_3")
group:getOrCreateLocation("Spike Torso Center 1"):setAttachmentName("winslow_Torso_C_1")
group:getOrCreateLocation("Spike Torso Center 2"):setAttachmentName("winslow_Torso_C_2")
group:getOrCreateLocation("Spike Torso Center 3"):setAttachmentName("winslow_Torso_C_3")
group:getOrCreateLocation("Spike Torso Center 4"):setAttachmentName("winslow_Torso_C_4")
group:getOrCreateLocation("Spike Torso Center 5"):setAttachmentName("winslow_Torso_C_5")
group:getOrCreateLocation("Spike L-Arm 1"):setAttachmentName("winslow_Arm_L_1")
group:getOrCreateLocation("Spike L-Arm 2"):setAttachmentName("winslow_Arm_L_2")
group:getOrCreateLocation("Spike L-Arm 3"):setAttachmentName("winslow_Arm_L_3")
group:getOrCreateLocation("Spike L-Arm 4"):setAttachmentName("winslow_Arm_L_4")
group:getOrCreateLocation("Spike L-Arm 5"):setAttachmentName("winslow_Arm_L_5")
group:getOrCreateLocation("Spike L-Arm 6"):setAttachmentName("winslow_Arm_L_6")
group:getOrCreateLocation("Spike L-Arm 7"):setAttachmentName("winslow_Arm_L_7")
group:getOrCreateLocation("Spike L-Arm 8"):setAttachmentName("winslow_Arm_L_8")
group:getOrCreateLocation("Spike Back 1"):setAttachmentName("winslow_back_1")
group:getOrCreateLocation("Spike Back 2"):setAttachmentName("winslow_back_2")
group:getOrCreateLocation("Spike Back 3"):setAttachmentName("winslow_back_3")
group:getOrCreateLocation("Spike Back 4"):setAttachmentName("winslow_back_4")
group:getOrCreateLocation("Spike Back 5"):setAttachmentName("winslow_back_5")
group:getOrCreateLocation("Spike Back 6"):setAttachmentName("winslow_back_6")
group:getOrCreateLocation("Spike L-Leg 1"):setAttachmentName("winslow_Leg_L_1")
group:getOrCreateLocation("Spike L-Leg 2"):setAttachmentName("winslow_Leg_L_2")
group:getOrCreateLocation("Spike R-Leg 1"):setAttachmentName("winslow_Leg_R_1")
group:getOrCreateLocation("Spike R-Leg 2"):setAttachmentName("winslow_Leg_R_2")
group:getOrCreateLocation("Spike R-Leg 3"):setAttachmentName("winslow_Leg_R_3")
group:getOrCreateLocation("Spike R-Arm 1"):setAttachmentName("winslow_Arm_R_1")
group:getOrCreateLocation("Spike R-Arm 2"):setAttachmentName("winslow_Arm_R_2")
group:getOrCreateLocation("Spike R-Arm 3"):setAttachmentName("winslow_Arm_R_3")
group:getOrCreateLocation("Spike R-Arm 4"):setAttachmentName("winslow_Arm_R_4")
group:getOrCreateLocation("Spike R-Arm 5"):setAttachmentName("winslow_Arm_R_5")
group:getOrCreateLocation("Spike R-Arm 6"):setAttachmentName("winslow_Arm_R_6")
group:getOrCreateLocation("Spike R-Arm 7"):setAttachmentName("winslow_Arm_R_7")