require("ItemTweaker_Copy_CC");

--AAS
--Food
TweakItem("AAS.MountainDew","DisplayCategory","FoodB");
TweakItem("AAS.Pepsi","DisplayCategory","FoodB");
TweakItem("AAS.RCCola","DisplayCategory","FoodB");
TweakItem("AAS.RootBeer","DisplayCategory","FoodB");
TweakItem("AAS.FantaGrape","DisplayCategory","FoodB");
TweakItem("AAS.GingerAle","DisplayCategory","FoodB");
TweakItem("AAS.CocaCola","DisplayCategory","FoodB");
TweakItem("AAS.DrPepper","DisplayCategory","FoodB");
TweakItem("AAS.DietCoke","DisplayCategory","FoodB");
TweakItem("AAS.MountainDewBox","DisplayCategory","FoodB");
TweakItem("AAS.PepsiBox","DisplayCategory","FoodB");
TweakItem("AAS.RCColaBox","DisplayCategory","FoodB");
TweakItem("AAS.RootBeerBox","DisplayCategory","FoodB");
TweakItem("AAS.FantaGrapeBox","DisplayCategory","FoodB");
TweakItem("AAS.CocaColaBox","DisplayCategory","FoodB");
TweakItem("AAS.DietCokeBox","DisplayCategory","FoodB");
TweakItem("AAS.DrPepperBox","DisplayCategory","FoodB");
TweakItem("AAS.GingerAleBox","DisplayCategory","FoodB");
--Junk
TweakItem("AAS.MountainDewEmpty","DisplayCategory","Junk");
TweakItem("AAS.PepsiEmpty","DisplayCategory","Junk");
TweakItem("AAS.RootBeerEmpty","DisplayCategory","Junk");
TweakItem("AAS.CocaColaEmpty","DisplayCategory","Junk");
TweakItem("AAS.DietCokeEmpty","DisplayCategory","Junk");
TweakItem("AAS.GingerAleEmpty","DisplayCategory","Junk");
TweakItem("AAS.DrPepperEmpty","DisplayCategory","Junk");
TweakItem("AAS.FantaGrapeEmpty","DisplayCategory","Junk");
TweakItem("AAS.RCColaEmpty","DisplayCategory","Junk");
TweakItem("AAS.CrushedCan","DisplayCategory","Junk");
