require("ItemTweaker_Copy_CC");

--ALECMODS
--Food
TweakItem("BottlingFish.BottlingFishFillet","DisplayCategory","FoodP");
TweakItem("BottlingFish.BottlingSalmon","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingChicken","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingSteak","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingFrogMeat","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingMeatPatty","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingMuttonChop","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingPorkChop","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingRabbitmeat","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingSmallanimalmeat","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingSmallbirdmeat","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingBacon","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingBaconBits","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingBaconRashers","DisplayCategory","FoodP");
TweakItem("Bottling.BottlingHam","DisplayCategory","FoodP");
--Misc
TweakItem("Base.JarLidBoxs","DisplayCategory","Misc");