require("ItemTweaker_Copy_CC");

--ARMORMOD
--Clothing
TweakItem("Armor.ArmorHardhat","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHelmbike","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHelmfootball","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHockeymask","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHelmmotorcycle","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHelmkevlar","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHelmswat","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHelmriot","DisplayCategory","ClothN");
TweakItem("Armor.ArmorHelmsamurai","DisplayCategory","ClothN");
TweakItem("Armor.ArmorWorkgloves","DisplayCategory","ClothN");
TweakItem("Armor.ArmorGlovekevlar","DisplayCategory","ClothN");
TweakItem("Armor.ArmorGloveriot","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmarmorkevlar","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmarmorswat","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmarmorriot","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmarmorsamurai","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmormilitaryjacket","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmorlightjacket","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmorleatherjacket","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmorkevlar","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmorswat","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmorriot","DisplayCategory","ClothN");
TweakItem("Armor.ArmorArmorsamurai","DisplayCategory","ClothN");
TweakItem("Armor.ArmorJeans","DisplayCategory","ClothN");
TweakItem("Armor.ArmorLegarmorkevlar","DisplayCategory","ClothN");
TweakItem("Armor.ArmorLegarmorswat","DisplayCategory","ClothN");
TweakItem("Armor.ArmorLegarmorriot","DisplayCategory","ClothN");
TweakItem("Armor.ArmorLegarmorsamurai","DisplayCategory","ClothN");
TweakItem("Armor.ArmorShieldriot","DisplayCategory","ClothP");
TweakItem("Armor.ArmorShieldwood","DisplayCategory","ClothP");
TweakItem("Armor.ArmorShieldtrashcanlid","DisplayCategory","ClothP");
