require("ItemTweaker_Copy_CC");

--BETTERBELTS
TweakItem("Base.Belt3","DisplayCategory","ClothN");
TweakItem("Base.Belt4","DisplayCategory","ClothN");
TweakItem("Base.HolsterSimpleL","DisplayCategory","ClothA");
TweakItem("Base.FirstAidKitB","DisplayCategory","Container");
TweakItem("Base.AFAK","DisplayCategory","Container");
TweakItem("Base.AFAKB","DisplayCategory","Container");
TweakItem("Base.ToolBoxB","DisplayCategory","Container");
TweakItem("Base.LunchboxB","DisplayCategory","Container");
TweakItem("Base.Lunchbox2B","DisplayCategory","Container");
TweakItem("Base.QuiverB","DisplayCategory","Container");
TweakItem("Base.PistolCase1B","DisplayCategory","Container");
TweakItem("Base.TentKitGreen","DisplayCategory","SurCamp");
TweakItem("Base.HookB","DisplayCategory","Craft");
TweakItem("Base.HookedWaterBottleEmptyOrange","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullOrange","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyYellow","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullYellow","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyGreen","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullGreen","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyPurple","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullPurple","DisplayCategory","FoodB");
TweakItem("Base.HookedWaterBottleEmptyRed","DisplayCategory","Container");
TweakItem("Base.HookedWaterBottleFullRed","DisplayCategory","FoodB");