require("ItemTweaker_Copy_CC");

--EXPLORINGTIME
--Mechanics
TweakItem("filcher.BottleWithGasPop","DisplayCategory","Mechanics");
TweakItem("filcher.BottleWithGasWater","DisplayCategory","Mechanics");
--Tools
TweakItem("filcher.Flare","DisplayCategory","Tool");
TweakItem("filcher.GasLantern","DisplayCategory","Tool");
TweakItem("filcher.GasLanternEmpty","DisplayCategory","Tool");
TweakItem("filcher.GasLanternLit","DisplayCategory","Tool");
TweakItem("filcher.TorchBranch","DisplayCategory","Tool");
TweakItem("filcher.TorchBranchLit","DisplayCategory","Tool");
TweakItem("filcher.TorchChairLeg","DisplayCategory","Tool");
TweakItem("filcher.TorchChairLegLit","DisplayCategory","Tool");
TweakItem("filcher.TorchPlank","DisplayCategory","Tool");
TweakItem("filcher.TorchPlankLit","DisplayCategory","Tool");
TweakItem("filcher.TorchTableLeg","DisplayCategory","Tool");
TweakItem("filcher.TorchTableLegLit","DisplayCategory","Tool");