require("ItemTweaker_Copy_CC");

--KCMCROSSBOW
--Crafting
TweakItem("KCMweapons.KCM_Flax","DisplayCategory","Craft");
TweakItem("KCMweapons.CrossbowBoltShaft","DisplayCategory","Craft");
TweakItem("KCMweapons.CrossbowBoltParts","DisplayCategory","Craft");
--Weapons
TweakItem("KCMweapons.CrossbowBolt","DisplayCategory","Ammo");
TweakItem("KCMweapons.CrossbowBoltBox","DisplayCategory","Ammo");
TweakItem("KCMweapons.CrossbowBoltLarge","DisplayCategory","Ammo");
TweakItem("KCMweapons.CrossbowBoltLargeBox","DisplayCategory","Ammo");
TweakItem("KCMweapons.WoodenBolt","DisplayCategory","Ammo");
TweakItem("KCMweapons.WoodenBoltBox","DisplayCategory","Ammo");
TweakItem("Base.KCM_IronSight","DisplayCategory","WepPart");
TweakItem("Base.KCM_x2Scope","DisplayCategory","WepPart");
TweakItem("Base.KCM_x4Scope","DisplayCategory","WepPart");
TweakItem("Base.KCM_x8Scope","DisplayCategory","WepPart");
TweakItem("Base.KCM_Sling","DisplayCategory","WepPart");
TweakItem("Base.KCM_FiberglassStock","DisplayCategory","WepPart");
TweakItem("Base.KCM_RedDot","DisplayCategory","WepPart");
TweakItem("KCMweapons.HandCrossbow","DisplayCategory","WepBow");
TweakItem("KCMweapons.LargeCrossbow","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Compound","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Compound02","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Handmade","DisplayCategory","WepBow");
TweakItem("KCMweapons.KCM_Handmade02","DisplayCategory","WepBow");
