require("ItemTweaker_Copy_CC");

--82OSHKOSHM911
TweakItem("OshkoshShirts.TShirt_OshkoshGray","DisplayCategory","ClothN");
TweakItem("OshkoshShirts.TShirt_OshkoshBlack","DisplayCategory","ClothN");
TweakItem("OshkoshShirts.TShirt_bknht","DisplayCategory","ClothN");
TweakItem("OshkoshShirts.Hoodie_OshkoshBlack","DisplayCategory","ClothN");
TweakItem("OshkoshShirts.HoodieDOWN_OshkoshBlack","DisplayCategory","ClothN");
TweakItem("OshkoshShirts.Hoodie_OshkoshGray","DisplayCategory","ClothN");
TweakItem("OshkoshShirts.HoodieDOWN_OshkoshGray","DisplayCategory","ClothN");
TweakItem("Base.V100Tire2","DisplayCategory","Mechanics");
TweakItem("Base.V100Tires2","DisplayCategory","Mechanics");
TweakItem("Base.V100Axle2","DisplayCategory","Mechanics");
TweakItem("Base.V100AxleSmall2","DisplayCategory","Mechanics");
TweakItem("Base.M911Trunk2","DisplayCategory","Mechanics");
TweakItem("Base.M911Toolbox2","DisplayCategory","Mechanics");
TweakItem("Base.M911SpareTire2","DisplayCategory","Mechanics");
--86OSHKOSHP19A
TweakItem("Base.V100Tire2","DisplayCategory","Mechanics");
TweakItem("Base.P19ARoofHatch2","DisplayCategory","Mechanics");
TweakItem("Base.P19ABigTrunk2","DisplayCategory","Mechanics");
TweakItem("Base.P19ASmallTrunk2","DisplayCategory","Mechanics");
