require("ItemTweaker_Copy_CC");

--SWATPACKREDUX
--Clothing
TweakItem("Base.SWATPad","DisplayCategory","ClothN");
TweakItem("Base.SwatNeck","DisplayCategory","ClothN");
TweakItem("Base.Hat_SwatGasMask","DisplayCategory","ClothN");
TweakItem("Base.SwatElbowPads","DisplayCategory","ClothN");
TweakItem("Base.SwatKneePads","DisplayCategory","ClothN");
TweakItem("Base.Trousers_Swat","DisplayCategory","ClothN");
TweakItem("Base.Shoes_RiotBoots","DisplayCategory","ClothN");
TweakItem("Base.Shoes_SwatBoots","DisplayCategory","ClothN");
TweakItem("Base.Gloves_SwatGloves","DisplayCategory","ClothN");
TweakItem("Base.Gloves_RiotGloves","DisplayCategory","ClothN");
TweakItem("Base.Hat_SwatHelmet","DisplayCategory","ClothN");
TweakItem("Base.Vest_BulletSwat","DisplayCategory","ClothN");
TweakItem("Base.Jacket_Swat","DisplayCategory","ClothN");
TweakItem("Base.Glasses_SwatGoggles","DisplayCategory","ClothN");
TweakItem("Base.Hat_Balaclava_Swat","DisplayCategory","ClothN");
TweakItem("Base.Hat_PoliceRiotHelmet","DisplayCategory","ClothN");
TweakItem("Base.Hat_SWATRiotHelmet","DisplayCategory","ClothN");
TweakItem("Base.Hat_SWATRiotHelmet2","DisplayCategory","ClothN");
TweakItem("Base.RiotArmorSuit","DisplayCategory","ClothN");
TweakItem("Base.Hat_Antibombhelmet","DisplayCategory","ClothN");
TweakItem("Base.AntibombSuit","DisplayCategory","ClothN");
TweakItem("Base.AntibombSuitP2","DisplayCategory","ClothN");
TweakItem("Base.SWATPouch","DisplayCategory","ClothA");
TweakItem("Base.Bag_BigSwatBag","DisplayCategory","ClothA");
TweakItem("Base.Bag_PoliceBag","DisplayCategory","ClothA");
--Weapons
TweakItem("Base.RubberShells","DisplayCategory","Ammo");
TweakItem("Base.RubberShellsBox","DisplayCategory","Ammo");
TweakItem("Base.RiotShieldSwat","DisplayCategory","WepShield");
TweakItem("Base.RiotShieldPolice","DisplayCategory","WepShield");
TweakItem("Base.RiotShotgun","DisplayCategory","WepFire");
TweakItem("Base.Co2ShortRiotShotgun","DisplayCategory","WepFire");
TweakItem("Base.SwatMP5","DisplayCategory","WepFire");
TweakItem("Base.9mmMp5Clip","DisplayCategory","Ammo");
TweakItem("Base.SwatStunGrenade","DisplayCategory","WepBomb");
TweakItem("Base.SwatFragGrenade","DisplayCategory","WepBomb");
TweakItem("Base.SwatSmokeGrenade","DisplayCategory","WepBomb");
