require("ItemTweaker_Copy_CC");

--TAPEDTVSHOWS
--Electronics
TweakItem("TapedTvShows.VideoTape1","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape2","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape3","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape4","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape5","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape6","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape7","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape8","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape9","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape10","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape11","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape12","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape13","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape14","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape15","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape16","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape17","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape18","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape19","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape20","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape21","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape22","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape23","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape24","DisplayCategory","Electronics");
TweakItem("TapedTvShows.VideoTape25","DisplayCategory","Electronics");
