require("ItemTweaker_Copy_CC");

--VFFOGSN
--Food
TweakItem("Base.StirFryBowl","DisplayCategory","FoodP");
TweakItem("Base.RoastedVegetablesBowl","DisplayCategory","FoodP");
TweakItem("Base.RosehipsDried","DisplayCategory","FoodN");
TweakItem("Base.GrapeLeavesDried","DisplayCategory","FoodN");
TweakItem("Base.VioletsDried","DisplayCategory","FoodN");
TweakItem("Base.Teabag_Medicinal","DisplayCategory","FoodB");
TweakItem("Base.Teabag_Energizing","DisplayCategory","FoodB");
TweakItem("Base.Teabag_MedicinalDried","DisplayCategory","FoodB");
TweakItem("Base.Teabag_EnergizingDried","DisplayCategory","FoodB");
TweakItem("Base.Tea_CommonMallow","DisplayCategory","FoodB");
TweakItem("Base.Tea_LemonGrass","DisplayCategory","FoodB");
TweakItem("Base.Tea_BlackSage","DisplayCategory","FoodB");
TweakItem("Base.Tea_Ginseng","DisplayCategory","FoodB");
TweakItem("Base.Tea_Medicinal","DisplayCategory","FoodB");
TweakItem("Base.Tea_Energizing","DisplayCategory","FoodB");
--Medical
TweakItem("Base.CommonMallowDried","DisplayCategory","Medical");
TweakItem("Base.LemonGrassDried","DisplayCategory","Medical");
TweakItem("Base.BlackSageDried","DisplayCategory","Medical");
TweakItem("Base.GinsengDried","DisplayCategory","Medical");
TweakItem("Base.PlantainDried","DisplayCategory","Medical");
TweakItem("Base.WildGarlicDried","DisplayCategory","Medical");
