-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["d_furniture_bedroom_01_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_01_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_02_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_02_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_03_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_03_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_04_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_04_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_05_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_05_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_storage_ddd_01_0"] = {{ name = "other", tiles = {"container_overlays_ddd_01_8", "container_overlays_ddd_01_0"} }}
overlayMap["furniture_storage_ddd_01_1"] = {{ name = "other", tiles = {"container_overlays_ddd_01_9", "container_overlays_ddd_01_1"} }}
overlayMap["furniture_storage_ddd_01_2"] = {{ name = "other", tiles = {"container_overlays_ddd_01_10", "container_overlays_ddd_01_2"} }}
overlayMap["furniture_storage_ddd_01_3"] = {{ name = "other", tiles = {"container_overlays_ddd_01_11", "container_overlays_ddd_01_3"} }}
overlayMap["furniture_storage_ddd_01_12"] = {{ name = "other", tiles = {"container_overlays_ddd_01_40", "container_overlays_ddd_01_32"} }}
overlayMap["furniture_storage_ddd_01_14"] = {{ name = "other", tiles = {"books&misc_01_24", "books&misc_01_28"} }}
overlayMap["furniture_storage_ddd_01_15"] = {{ name = "other", tiles = {"books&misc_01_27", "books&misc_01_28"} }}
overlayMap["furniture_storage_ddd_01_24"] = {{ name = "other", tiles = {"container_overlays_ddd_01_24", "container_overlays_ddd_01_16"} }}
overlayMap["furniture_storage_ddd_01_25"] = {{ name = "other", tiles = {"container_overlays_ddd_01_25", "container_overlays_ddd_01_17"} }}
overlayMap["furniture_storage_ddd_01_26"] = {{ name = "other", tiles = {"container_overlays_ddd_01_26", "container_overlays_ddd_01_18"} }}
overlayMap["furniture_storage_ddd_01_27"] = {{ name = "other", tiles = {"container_overlays_ddd_01_27", "container_overlays_ddd_01_19"} }}
overlayMap["furniture_storage_ddd_01_48"] = {{ name = "other", tiles = {"container_overlays_ddd_01_60", "container_overlays_ddd_01_60"} }}
overlayMap["furniture_storage_ddd_01_51"] = {{ name = "other", tiles = {"container_overlays_ddd_01_59", "container_overlays_ddd_01_59"} }}
overlayMap["furniture_storage_ddd_01_53"] = {{ name = "other", tiles = {"container_overlays_ddd_01_61", "container_overlays_ddd_01_61"} }}
overlayMap["furniture_storage_ddd_01_54"] = {{ name = "other", tiles = {"container_overlays_ddd_01_62", "container_overlays_ddd_01_62"} }}
overlayMap["furniture_storage_ddd_01_55"] = {{ name = "other", tiles = {"container_overlays_ddd_01_63", "container_overlays_ddd_01_63"} }}
overlayMap["industry_dirkea_ddd_01_12"] = {{ name = "other", tiles = {"container_overlays_ddd_01_12", "container_overlays_ddd_01_4"} }}
overlayMap["industry_dirkea_ddd_01_13"] = {{ name = "other", tiles = {"container_overlays_ddd_01_13", "container_overlays_ddd_01_5"} }}
overlayMap["industry_dirkea_ddd_01_14"] = {{ name = "other", tiles = {"container_overlays_ddd_01_6", "container_overlays_ddd_01_14"} }}
overlayMap["industry_dirkea_ddd_01_15"] = {{ name = "other", tiles = {"container_overlays_ddd_01_7", "container_overlays_ddd_01_15"} }}
overlayMap["industry_dirkea_ddd_01_24"] = {{ name = "other", tiles = {"container_overlays_ddd_01_20", "container_overlays_ddd_01_20"} }, { name = "other", tiles = {"container_overlays_ddd_01_28", "container_overlays_ddd_01_28"} }}
overlayMap["industry_dirkea_ddd_01_25"] = {{ name = "other", tiles = {"container_overlays_ddd_01_21", "container_overlays_ddd_01_21"} }, { name = "other", tiles = {"container_overlays_ddd_01_29", "container_overlays_ddd_01_29"} }}
overlayMap["industry_dirkea_ddd_01_26"] = {{ name = "other", tiles = {"container_overlays_ddd_01_22", "container_overlays_ddd_01_22"} }, { name = "other", tiles = {"container_overlays_ddd_01_30", "container_overlays_ddd_01_30"} }}
overlayMap["industry_dirkea_ddd_01_27"] = {{ name = "other", tiles = {"container_overlays_ddd_01_23", "container_overlays_ddd_01_23"} }, { name = "other", tiles = {"container_overlays_ddd_01_31", "container_overlays_ddd_01_31"} }}
overlayMap["industry_dirkea_ddd_01_37"] = {{ name = "other", tiles = {"container_overlays_ddd_01_36", "container_overlays_ddd_01_44"} }, { name = "other", tiles = {"container_overlays_ddd_01_37", "container_overlays_ddd_01_45"} }}
overlayMap["industry_dirkea_ddd_01_38"] = {{ name = "other", tiles = {"container_overlays_ddd_01_38", "container_overlays_ddd_01_46"} }, { name = "other", tiles = {"container_overlays_ddd_01_39", "container_overlays_ddd_01_47"} }}
overlayMap["industry_railroad_ddd_01_28"] = {{ name = "other", tiles = {"container_overlays_ddd_01_54", "container_overlays_ddd_01_54"} }}
overlayMap["industry_railroad_ddd_01_29"] = {{ name = "other", tiles = {"container_overlays_ddd_01_55", "container_overlays_ddd_01_55"} }}
overlayMap["industry_railroad_ddd_01_36"] = {{ name = "other", tiles = {"container_overlays_ddd_01_52", "container_overlays_ddd_01_52"} }}
overlayMap["industry_railroad_ddd_01_37"] = {{ name = "other", tiles = {"container_overlays_ddd_01_53", "container_overlays_ddd_01_53"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
