-- pull the vehicle distributions into a local table
local distributionTable = VehicleDistributions[1]


-- Emergency Vehicles
distributionTable["92crownvicRosewood"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicBlackwood"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicBlackwoodTransit"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicRiverside"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicIvy"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicFrankfort"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicGrapeseed"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicMarchRidge"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicBedFalls"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicKnoxSheriff"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicCrosstown"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicMuldraugh"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicWestPoint"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicWestPointMunicipal"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicWestPointAnimal"] = distributionTable["VanAmbulance"]
distributionTable["92crownvicRavenCreek"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicRavenCreekTransit"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicJeffersonSheriff"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["86econolineambulanceGrapeseed"] = distributionTable["VanAmbulance"]
distributionTable["86econolineambulanceWestPoint"] = distributionTable["VanAmbulance"]
distributionTable["86econolineambulanceBlackwood"] = distributionTable["VanAmbulance"]
distributionTable["80f350ambulanceRosewood"] = distributionTable["VanAmbulance"]
distributionTable["86econolineMarchRidge"] = distributionTable["VanAmbulance"]
distributionTable["86econolineBlackwood"] = distributionTable["VanAmbulance"]
distributionTable["firepumperWPFD"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["firepumperGrapeseed"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["firepumperRosewood"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["firepumperBlackwood"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["93explorerDOC"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93explorerRosewood"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicDOC"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["87capriceDOC"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["87capriceRosewood"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["87capriceMarchRidge"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93explorerWestPoint"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["73falconDixie"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["85vicDixie"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["85vicWestPoint"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["91crxDARE"] = distributionTable["VanAmbulance"]
distributionTable["92wranglerWestPoint"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicMetro"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicMetroAiport"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicRavenCreekPort"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["chevystepvanLPD"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvicJCPD"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["87c10JCPD"] = { Normal = VehicleDistributions.Military; }
distributionTable["86econolineLEMS"] = distributionTable["VanAmbulance"]
distributionTable["80f350ambulanceLEMS"] = distributionTable["VanAmbulance"]
distributionTable["80f350ambulanceJCEMS"] = distributionTable["VanAmbulance"]
distributionTable["86econolineambulanceLEMS"] = distributionTable["VanAmbulance"]
distributionTable["firepumperLFD"] = distributionTable["PickUpTruckLightsFire"]